# Generated by Django 5.1.15 on 2026-06-08 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('visitor_name', models.CharField(max_length=120, verbose_name='Nom du visiteur')),
                ('visitor_email', models.EmailField(max_length=254, verbose_name='E-mail du visiteur')),
                ('page', models.CharField(blank=True, max_length=300, verbose_name="Page d'origine")),
                ('is_closed', models.BooleanField(default=False, verbose_name='Clôturée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation (chat)',
                'verbose_name_plural': 'Conversations (chat)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('visitor', 'Visiteur'), ('team', 'Équipe Horus-Lab')], default='visitor', max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['id'],
            },
        ),
    ]
