# Generated by Django 5.1.15 on 2026-06-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail du visiteur'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='visitor_name',
            field=models.CharField(blank=True, default='Visiteur', max_length=120, verbose_name='Nom du visiteur'),
        ),
    ]
