# Generated by Django 5.1.15 on 2026-07-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_visitor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name="Slug de l'article")),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Titre (repère admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Forum — fil d'un article",
                'verbose_name_plural': 'Forum — fils par article',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='Visiteur', max_length=120, verbose_name='Auteur')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail (privé, jamais public)')),
                ('text', models.TextField()),
                ('is_staff', models.BooleanField(default=False, verbose_name="Réponse de l'équipe Horus-Lab")),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Masqué (modération)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='chat.forumthread')),
            ],
            options={
                'verbose_name': 'Forum — message',
                'verbose_name_plural': 'Forum — messages',
                'ordering': ['id'],
            },
        ),
    ]
