# Generated by Django 5.1.15 on 2026-07-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_forumthread_forumpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
