# Generated by Django 5.1.15 on 2026-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=160)),
                ('title_en', models.CharField(max_length=160)),
                ('category_fr', models.CharField(max_length=80)),
                ('category_en', models.CharField(max_length=80)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('result_fr', models.CharField(blank=True, max_length=80)),
                ('result_en', models.CharField(blank=True, max_length=80)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('icon', models.CharField(default='code', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['order'],
            },
        ),
    ]
