# Generated by Django 5.1.15 on 2026-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Réalisation', 'verbose_name_plural': 'Réalisations'},
        ),
        migrations.AddField(
            model_name='project',
            name='client_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='client_fr',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient',
            field=models.CharField(default='from-brand-700 via-brand-500 to-sky', help_text="Gradient Tailwind (ex. 'from-brand-700 via-brand-500 to-sky'). Sera appliqué via bg-gradient-to-br côté frontend.", max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Affiche en grand sur la home (1 seul attendu).'),
        ),
        migrations.AddField(
            model_name='project',
            name='role_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='role_fr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_fr',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Lien public optionnel.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(default='code', help_text="Clé d'icône : code, layers, cog, spark, eye, globe, check", max_length=20),
        ),
    ]
