# Generated by Django 5.1.15 on 2026-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_fr', models.CharField(blank=True, max_length=120)),
                ('eyebrow_en', models.CharField(blank=True, max_length=120)),
                ('title_lead_fr', models.CharField(blank=True, max_length=200)),
                ('title_lead_en', models.CharField(blank=True, max_length=200)),
                ('title_highlight_fr', models.CharField(blank=True, max_length=200)),
                ('title_highlight_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_fr', models.TextField(blank=True)),
                ('subtitle_en', models.TextField(blank=True)),
                ('cta_primary_fr', models.CharField(blank=True, max_length=80)),
                ('cta_primary_en', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_fr', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_en', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Hero — textes',
                'verbose_name_plural': 'Hero — textes',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('alt_fr', models.CharField(blank=True, max_length=160)),
                ('alt_en', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero — image',
                'verbose_name_plural': 'Hero — images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('label_fr', models.CharField(max_length=80)),
                ('label_en', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hero — statistique',
                'verbose_name_plural': 'Hero — statistiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Étape de méthode',
                'verbose_name_plural': 'Étapes de méthode',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list, help_text='Liste de mots-clés')),
                ('icon', models.CharField(default='code', help_text="Clé d'icône : code, layers, cog, spark", max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Horus-Lab', max_length=80)),
                ('tagline_fr', models.CharField(blank=True, max_length=200)),
                ('tagline_en', models.CharField(blank=True, max_length=200)),
                ('about_fr', models.TextField(blank=True)),
                ('about_en', models.TextField(blank=True)),
                ('email', models.EmailField(default='contact@horus-lab.com', max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=40)),
                ('phone_secondary', models.CharField(blank=True, max_length=40)),
                ('location_fr', models.CharField(blank=True, max_length=120)),
                ('location_en', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Réglages du site',
                'verbose_name_plural': 'Réglages du site',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_fr', models.TextField()),
                ('quote_en', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('role_fr', models.CharField(blank=True, max_length=120)),
                ('role_en', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
