# Generated by Django 5.1.15 on 2026-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_achievement_partner_teammember_techstackitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo_path',
            field=models.CharField(blank=True, help_text='Chemin /public (ex. /Nos-partenaires/xxx.png). Utilisé si aucun logo uploadé.', max_length=300, verbose_name='Logo (chemin statique)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='badge_en',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='teammember',
            name='badge_fr',
            field=models.CharField(blank=True, help_text='Ex. Co-fondateur', max_length=40),
        ),
        migrations.AddField(
            model_name='teammember',
            name='gradient',
            field=models.CharField(blank=True, help_text="Classes Tailwind du dégradé (repli d'avatar si pas de photo).", max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo_path',
            field=models.CharField(blank=True, help_text='Chemin /public (ex. /A-propos/xxx.png). Utilisé si aucune photo uploadée.', max_length=300, verbose_name='Photo (chemin statique)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_path',
            field=models.CharField(blank=True, help_text='Chemin /public (ex. /Temoignages/xxx.png). Utilisé si aucun avatar uploadé.', max_length=300, verbose_name='Image (chemin statique)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_logo',
            field=models.BooleanField(default=False, help_text="Affiche l'image comme logo (pastille blanche) au lieu d'une photo.", verbose_name='Logo institutionnel'),
        ),
    ]
