# Generated by Django 5.1.15 on 2026-06-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('type', models.CharField(choices=[('emploi', 'Emploi'), ('stage', 'Stage')], default='emploi', max_length=10, verbose_name='Type')),
                ('position', models.CharField(blank=True, max_length=160, verbose_name='Poste / domaine visé')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('document', models.FileField(upload_to='applications/%Y/%m/', verbose_name='Dossier (ZIP)')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('reviewing', "En cours d'examen"), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='new', max_length=12, verbose_name='Statut')),
                ('page', models.CharField(blank=True, max_length=300, verbose_name="Page d'origine")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
            },
        ),
    ]
