# Generated by Django 5.1.15 on 2026-07-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Identifiant')),
                ('name_fr', models.CharField(max_length=80, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=80, verbose_name='Nom (EN)')),
                ('tagline_fr', models.CharField(blank=True, max_length=160, verbose_name='Accroche (FR)')),
                ('tagline_en', models.CharField(blank=True, max_length=160, verbose_name='Accroche (EN)')),
                ('icon_key', models.CharField(choices=[('code', 'Code'), ('layers', 'Calques'), ('spark', 'Étincelle'), ('eye', 'Œil'), ('cog', 'Engrenage')], default='code', max_length=10, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Domaine de formation',
                'verbose_name_plural': 'Domaines de formation',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Identifiant')),
                ('title_fr', models.CharField(max_length=160, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=160, verbose_name='Titre (EN)')),
                ('subtitle_fr', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre (FR)')),
                ('subtitle_en', models.CharField(blank=True, max_length=200, verbose_name='Sous-titre (EN)')),
                ('level_fr', models.CharField(default='Débutant', max_length=40, verbose_name='Niveau (FR)')),
                ('level_en', models.CharField(default='Beginner', max_length=40, verbose_name='Niveau (EN)')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Durée (heures)')),
                ('lessons_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de leçons')),
                ('price_fr', models.CharField(default='Gratuit', max_length=40, verbose_name='Prix (FR)')),
                ('price_en', models.CharField(default='Free', max_length=40, verbose_name='Prix (EN)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuit')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('image', models.CharField(blank=True, help_text='Chemin statique frontend (ex. /img/xxx.jpg) ou URL absolue.', max_length=300, verbose_name='Image (chemin ou URL)')),
                ('instructor_name', models.CharField(default='Équipe Horus-Lab', max_length=120, verbose_name='Formateur — nom')),
                ('instructor_role_fr', models.CharField(blank=True, max_length=160, verbose_name='Formateur — rôle (FR)')),
                ('instructor_role_en', models.CharField(blank=True, max_length=160, verbose_name='Formateur — rôle (EN)')),
                ('intro_fr', models.TextField(blank=True, verbose_name='Introduction (FR)')),
                ('intro_en', models.TextField(blank=True, verbose_name='Introduction (EN)')),
                ('learn_fr', models.JSONField(blank=True, default=list, verbose_name='Objectifs (FR)')),
                ('learn_en', models.JSONField(blank=True, default=list, verbose_name='Objectifs (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category', verbose_name='Domaine')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=160, verbose_name='Titre (FR)')),
                ('title_en', models.CharField(max_length=160, verbose_name='Titre (EN)')),
                ('lessons_fr', models.JSONField(blank=True, default=list, verbose_name='Leçons (FR)')),
                ('lessons_en', models.JSONField(blank=True, default=list, verbose_name='Leçons (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='courses.course', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order', 'id'],
            },
        ),
    ]
