# Generated by Django 5.1.15 on 2026-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_drop_legacy_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Vraie vidéo de cours (YouTube) — lecteur intégré sur la page du cours.', max_length=300, verbose_name='Vidéo du cours (YouTube)'),
        ),
    ]
