# Generated by Django 5.1.15 on 2026-05-27 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('body_fr', models.TextField(help_text='Corps court, 1–3 phrases.')),
                ('body_en', models.TextField(help_text='Short body, 1–3 sentences.')),
                ('tag_fr', models.CharField(default='Actualité', help_text='Étiquette courte (ex. Produit, Lancement, Partenariat).', max_length=40)),
                ('tag_en', models.CharField(default='News', max_length=40)),
                ('url', models.URLField(blank=True, help_text='Lien externe optionnel (site, communiqué, etc.).')),
                ('published_at', models.DateField(default=django.utils.timezone.now, help_text="Date d'affichage de la news (utilisée pour le tri).")),
                ('is_published', models.BooleanField(default=True, help_text='Décocher pour masquer sans supprimer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
